"""Schema definitions for novel generation."""

from novel_generator.schema.chapter import ChapterEvent, ChapterSummary, EventType
from novel_generator.schema.character import Character, CharacterState, CharacterVoice
from novel_generator.schema.character_state_contract import (
    CHARACTER_STATE_ENTRY_ADAPTER,
    BaseCharacterStateEntry,
    BeliefEntry,
    CharacterStateEntry,
    CharacterStateLedgerBinding,
    CharacterStatePersistenceManifest,
    CharacterStatePartialRecord,
    CharacterStateQuery,
    CharacterStateQueryResponse,
    CharacterStateQuerySourceView,
    CharacterStateQueryTimelineView,
    CharacterStateSourceFilter,
    CharacterStateTimelineFilter,
    LedgerStorageFormat,
    MemoryEntry,
    MemoryExperienceMode,
    ObjectiveFactEntry,
    TimelineQueryRelation,
    UtteranceEntry,
)
from novel_generator.schema.character_state_schema import (
    BeliefStateProvenance,
    CanonicalFactProvenance,
    CanonicalFactRecordSchema,
    CharacterBeliefStateSchema,
    CharacterMemoryStateSchema,
    CharacterStateDivergenceCause,
    MemoryStateProvenance,
    StateEvidenceProvenance,
)
from novel_generator.schema.character_state_metadata import (
    CharacterStateLifecycle,
    CharacterStateLifecycleStatus,
    CharacterStateProvenance,
    CharacterStateProvenanceKind,
    CharacterStateRecordMetadata,
    CharacterStateRecordType,
    SceneReference,
)
from novel_generator.schema.foreshadowing import Foreshadowing, ForeshadowingAction
from novel_generator.schema.novel import NovelSeed, PlotArc
from novel_generator.schema.simulation_event import (
    CharacterStateReference,
    SimulationBeliefUpdate,
    SimulationMemoryUpdate,
    SimulationObjectiveFactUpdate,
    SimulationStateEvent,
)

__all__ = [
    "Character",
    "CharacterVoice",
    "CharacterState",
    "CharacterStateLifecycle",
    "CharacterStateLifecycleStatus",
    "CharacterStateProvenance",
    "CharacterStateProvenanceKind",
    "CharacterStateRecordMetadata",
    "CharacterStateRecordType",
    "SceneReference",
    "BaseCharacterStateEntry",
    "ObjectiveFactEntry",
    "MemoryEntry",
    "BeliefEntry",
    "CanonicalFactRecordSchema",
    "CharacterMemoryStateSchema",
    "CharacterBeliefStateSchema",
    "UtteranceEntry",
    "CharacterStateEntry",
    "CHARACTER_STATE_ENTRY_ADAPTER",
    "MemoryExperienceMode",
    "CharacterStateDivergenceCause",
    "StateEvidenceProvenance",
    "CanonicalFactProvenance",
    "MemoryStateProvenance",
    "BeliefStateProvenance",
    "TimelineQueryRelation",
    "LedgerStorageFormat",
    "CharacterStateLedgerBinding",
    "CharacterStatePersistenceManifest",
    "CharacterStateSourceFilter",
    "CharacterStateTimelineFilter",
    "CharacterStateQuery",
    "CharacterStateQuerySourceView",
    "CharacterStateQueryTimelineView",
    "CharacterStatePartialRecord",
    "CharacterStateQueryResponse",
    "Foreshadowing",
    "ForeshadowingAction",
    "ChapterSummary",
    "ChapterEvent",
    "EventType",
    "CharacterStateReference",
    "SimulationObjectiveFactUpdate",
    "SimulationMemoryUpdate",
    "SimulationBeliefUpdate",
    "SimulationStateEvent",
    "NovelSeed",
    "PlotArc",
]
